name: pats_space
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/focus_pairs/pair_01/
    - assets/images/focus_pairs/pair_02/
    - assets/images/focus_pairs/pair_03/
    - assets/images/focus_pairs/pair_04/
    - assets/images/focus_pairs/pair_05/
    - assets/images/focus_pairs/pair_06/
    - assets/images/focus/stamps/character/
    - assets/images/social_focus/background/
    - assets/images/social_focus/decor/
    - assets/images/social_focus/furniture/desks/
    - assets/images/social_focus/characters/reading/
    - assets/images/social_focus/characters/writing/
    - assets/images/social_focus/characters/coding/
    - assets/images/social_focus/characters/sleeping/
    - assets/images/social_focus/accessories/
    - assets/images/social_focus/placeholders/
    - assets/images/garden/backgrounds/
    - assets/images/garden/pots/default/
    - assets/images/garden/pots/
    - assets/images/garden/decorations/
    - assets/images/garden/plants/default/stages/
    - assets/images/garden/plants/tulip/stages/
    - assets/images/garden/plants/clover/stages/
    - assets/images/garden/plants/sunflower/stages/
    - assets/images/garden/plants/hanging_flower/stages/
    - assets/images/garden/ui/
