// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwX2ATyoi5yZ0X14jVeQ2daKkd0S3LIkA',
    appId: '1:1051905230507:android:1b74b712529e2c6b4199ee',
    messagingSenderId: '1051905230507',
    projectId: 'patsspace-app',
    storageBucket: 'patsspace-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMVtXr81Otbvjnh_OLs44Lwdd2sfoex-A',
    appId: '1:1051905230507:ios:7f4ba15b9f0773d04199ee',
    messagingSenderId: '1051905230507',
    projectId: 'patsspace-app',
    storageBucket: 'patsspace-app.firebasestorage.app',
    iosBundleId: 'com.patsspace.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMVtXr81Otbvjnh_OLs44Lwdd2sfoex-A',
    appId: '1:1051905230507:ios:7f4ba15b9f0773d04199ee',
    messagingSenderId: '1051905230507',
    projectId: 'patsspace-app',
    storageBucket: 'patsspace-app.firebasestorage.app',
    iosBundleId: 'com.patsspace.app',
  );
}
